apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://cl-akec96-cf17e901.hcp.eastus.azmk8s.io:443
  name: CL-AKS01
contexts:
- context:
    cluster: CL-AKS01
    user: clusterUser_RG01_CL-AKS01
  name: CL-AKS01
current-context: CL-AKS01
kind: Config
preferences: {}
users:
- name: clusterUser_RG01_CL-AKS01
  user:
    client-certificate-data: DATA+OMITTED
    client-key-data: DATA+OMITTED
    token: REDACTED