apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: api-produto

resources:
  - ../../base

# Ambiente de desenvolvimento: 1 réplica
replicas:
  - name: api
    count: 1

images:
  - name: rsprazeres/api-produto
    newTag: latest
